version: '3'
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'characters'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  mud:
    container_name: gmud
    build: .
    ports:
      - "1234:1234" # fgtrace but doesnt work
      - "2222:2222"
      - "8081:8081"
    volumes:
    - .:/code
    command: "./app"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
volumes:
  my-db: